config/routes.rb
Rails.application.routes.draw do

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'productdisplays/home'

  get 'admindashboards/show'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'application#hello'
  #devise_for:users
  #devise_for :users, :controllers => { :registrations => "users/registrations",sessions: "users/sessions" }
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "users/registrations",:sessions=>"users/sessions" }
  root 'dashboard#index'

  get 'products99/:id', to: 'dashboard#list_products',as: :list_products

  get 'product_detail/:id' , to:'dashboard#product_detail' , as: :product_detail

  get 'carts/invoicepage'

  #get 'dashboard/list_products/:id'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" ,:registrations => "users/registrations"}

  get 'users/auth/facebook', to: 'sessions#create'
  #get "auth/:provider/callback", to: "sessions#create"
  get 'users/auth/github', to: 'sessions#create'
  # get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  #get '/auth/:provider/callback', to: 'sessions#create'

  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_up', :to => 'devise/registrations#new'
    get 'sign_in', :to => 'devise/sessions#new'
    get 'users/sign_out', :to => 'devise/sessions#destroy'
  end
  #root 'dashboard#index'

  resources :categories
  resources :products
  #resources :carts, only: [:show]
  resources :carts
  resources :order_items, only: [:create, :update, :destroy]

  get "user_mailer/invoicemail"
  get "carts/createinvoice"

  resources :registrations, only: [:new, :create]

  #get "registrations/new"
  #get "registrations/create"
  #get "registrations/:id", to:'registrations/create' , as: :registrations_detail


  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get  '/signup',  to: 'users#new'
  #get '/signup',  to: 'users#edit'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @categories=Category.all
    @order=current_order
    @order_items=current_order.order_items
  end

  def invoicepage
    @categories=Category.all
    @products = Product.all
    @order=current_order
    puts @order.inspect
    puts '-----------'
    @order_items=current_order.order_items
    #@product_list= Product.find(params[:id])
    puts @order_items.inspect
    puts '-----------'
    @current_user= current_user
    puts @current_user.inspect
    UserMailer.invoicemail(@current_user,@categories,@products,@order,@order_items).deliver
  end

  # def createinvoice
  #   @user = current_user
  #
  #   respond_to do |format|
  #     if @user.save
  #       # Tell the UserMailer to send a welcome email after save
  #       UserMailer.invoicemail.deliver_now
  #
  #       format.html { redirect_to(@user, notice: 'Invoice was successfuly send') }
  #       format.json { render json: @user, status: :created, location: @user }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="container">

  <div class="box-body">
    <div class="col-xs-8">
      <h4><%= product.prod_name %></h4>
    </div>
    <div class="span4">
      <%= image_tag product.avatar.url %>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%=  order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity",  class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.prod_name}' from your cart?" }, method: :delete, remote:true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%=  order_item.total_price %></span></h4>
        <h4 class="text-right">SubTotal Price: <span style="color: green"><%=  @order.subtotal %></span></h4>
      <% end %>
    </div>
  </div>
   <div class="btn-group">
    <%= link_to "Submit", carts_invoicepage_path, { data: { confirm: "Are you sure you wish to submit order " }, class: "btn btn-danger" } %>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/invoicepage.html.erb
<!--<h3> Products under this order </h3>-->
<%#= current_order.order_items.each{ |order_item| puts order_item } %>

<%#= puts @order.order_id %>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
    		<div class="invoice-title">
    			<h4 class="text-center" style=" display: inline-block;"><b>Invoice</b></h4><h3 class="pull-right">Order Id:<%= @order.id%></h3>
    		</div>
    		<hr>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    				<strong>Billed To:</strong><br>
    					<h4><%= User.find(current_user.id).first_name %>   <%= User.find(current_user.id).last_name %></h4>
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
        			<strong>Shipped To:</strong><br>
    					<%= User.find(current_user.id).first_name %>   <%= User.find(current_user.id).last_name %><br>
    					1234 Main<br>
    					Apt. 4B<br>
    					Springfield, ST 54321
    				</address>
    			</div>
    		</div>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    					<strong>Registered Email:</strong><br>
    					<%= User.find(current_user.id).email %>
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
    					<strong>Order Date:</strong><br>
    					<%=@order.created_at%><br><br>
    				</address>
    			</div>
    		</div>
    	</div>

    </div>

    <div class="row">
      <% current_order.order_items.each do |order_item| %>
    	<div class="col-md-12">
    		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h3 class="panel-title"><strong>Order placed on <%=@order.created_at%></strong></h3>
    			</div>
    			<div class="panel-body">
    				<div class="table-responsive">
    					<table class="table table-condensed" >
    						<thead>
                                <tr>
        							<td><strong>Product</strong></td>
        							<td class="text-center"><strong>Price</strong></td>
        							<td class="text-center"><strong>Quantity</strong></td>
        							<td class="text-right"><strong>Totals</strong></td>
                                </tr>
    						</thead>
    						<tbody>
    							<!-- foreach ($order->lineItems as $line) or some such thing here -->
    							<tr>
    								<td><%=Product.find(order_item.product_id).prod_name%></td>
    								<td class="text-center"><%= order_item.unit_price %></td>
    								<td class="text-center"><%= order_item.quantity %></td>
    								<td class="text-right"><%= order_item.total_price %></td>
    							</tr>

    						</tbody>
    					</table>
    				</div>
    			</div>
    		</div>
    	</div>
        <%end%>
    </div>

    <div class="invoice-title">
      <h3 class="pull-right">SubTotal:<%= @order.subtotal%></h3>
    </div>

    <div class="row">
        <div class="col-md-12">
           <div class="col-md-4">
             <h3 class="text-center">Order Summary</h3><hr>
             <div class="pull-left"><h4>Subtotal</h4> </div>
             <div class="pull-right"><h4 class="text-right"><%= @order.subtotal%></h4></div>
             <div class="clearfix"></div>
             <div class="pull-left"><h4>Tax</h4> </div>
             <div class="pull-right"><h4 class="text-right">0.0</h4></div>
             <div class="clearfix"></div>
             <div class="pull-left"><h4>Order Total</h4> </div>
             <div class="pull-right"><h4 class="text-right"><%= @order.subtotal%></h4></div>
             <div class="clearfix"></div>
         </div>
         <div class="col-md-4 offset-md-1">
             <h3 class="text-center">Payment Type</h3><hr>
             <div class="text-center">
                 <strong>Paid by Credit Card</strong><br>
              </div>
         </div>
         <div class="col-md-4 offset-md-2">
             <h3 class="text-center">Other Info</h3><hr>
             <address>
                 <strong>Billed To:</strong><br>
                 <%= User.find(current_user.id).first_name %>   <%= User.find(current_user.id).last_name %><br>
                 1234 Main<br>
                 Apt. 4B<br>
                 Springfield, ST 54321
              </address>
         </div>
     </div>
     <div class="btn-group">
       <%= link_to "Payment", new_registration_path, { data: { confirm: "Are you sure you wish to submit order " }, class: "btn btn-danger" } %>
     </div>
</div>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render 'carts/shopping_cart' %>
</div>