config/routes.rb
Rails.application.routes.draw do

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'productdisplays/home'

  get 'admindashboards/show'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'application#hello'
  #devise_for:users
  #devise_for :users, :controllers => { :registrations => "users/registrations",sessions: "users/sessions" }
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "users/registrations",:sessions=>"users/sessions" }
  root 'dashboard#index'

  get 'products99/:id', to: 'dashboard#list_products',as: :list_products

  get 'product_detail/:id' , to:'dashboard#product_detail' , as: :product_detail

  get 'carts/invoicepage'

  #get 'dashboard/list_products/:id'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" ,:registrations => "users/registrations"}

  get 'users/auth/facebook', to: 'sessions#create'
  #get "auth/:provider/callback", to: "sessions#create"
  get 'users/auth/github', to: 'sessions#create'
  # get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  #get '/auth/:provider/callback', to: 'sessions#create'

  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_up', :to => 'devise/registrations#new'
    get 'sign_in', :to => 'devise/sessions#new'
    get 'users/sign_out', :to => 'devise/sessions#destroy'
  end
  #root 'dashboard#index'

  resources :categories
  resources :products
  #resources :carts, only: [:show]
  resources :carts
  resources :order_items, only: [:create, :update, :destroy]

  get "user_mailer/invoicemail"
  get "carts/createinvoice"

  resources :registrations, only: [:new, :create]

  #get "registrations/new"
  #get "registrations/create"
  #get "registrations/:id", to:'registrations/create' , as: :registrations_detail


  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get  '/signup',  to: 'users#new'
  #get '/signup',  to: 'users#edit'

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :order_items

    has_attached_file :avatar
    #has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  #  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

      validates :prod_name, presence:true
      validates :price,  presence:true, numericality: { greater_than_or_equal_to: 0}
      validates :color,  presence:true
      validates :quantity,  presence:true, numericality: { greater_than: 0}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout :layout_by_resource

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def layout_by_resource
    if current_user.has_role? :admin
       "adminshow"
    end
  end


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    #@categories = Category.find(params[:category_id])
    #@product = @categories.products.build(product_params)
    #@product.category_id = params[:category_id]

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.category_id = params[:category_id]
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:prod_name, :price, :color, :quantity,:avatar, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :category_name, product.category_id), {}, class: "form-control selectpicker" %>

  </div>

  <div class="form-group">
    <%= form.label :prod_name, "Product Name" %>
    <%= form.text_field :prod_name, id: :product_prod_name , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :color %>
    <%= form.text_field :color, id: :product_color, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity ,min: 0, max: 99, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<div class="container">
<h1>Editing Product</h1>

<%= render 'form', product: @product %>
<br>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><h1><% if current_user.has_role? :admin %>
              <%= link_to 'New Product', new_product_path %>
            <%end%></h1>
      </li>


    </ul>
  </nav>
  <h1 class="breadcrumb">
      <span>Products</span>
  </h1>

<div class="box-body">
<table id="example2" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Category</th>
      <th>Prod Name</th>
      <th>Price</th>
      <th>Color</th>
      <th>Quantity</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
      <!--  <td><%#= product.category_id %></td>-->
        <td><%= link_to Category.find(product.category_id).category_name, category_path(product.category_id) %></td>
        <td><%= product.prod_name %></td>
        <td><%= product.price %></td>
        <td><%= product.color %></td>
        <td><%= product.quantity %></td>
        <% if current_user.has_role? :admin %>
        <!--  <td><%#= link_to 'Show', product %></td>
          <td><%#= link_to 'Edit', edit_product_path(product) %></td>
          <!--<td><%#= link_to "Destroy", product, method: :delete %></td> -->
        <!--  <td><%#= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->

          <td><div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Action
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li><%= link_to 'Show', product %></li>
                    <li><%= link_to 'Edit', edit_product_path(product) %></li>
                    <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </div>
          </td>

        <% else%>
          <!--<td><%#= link_to 'Show', product %></td>-->
          <td><div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Action
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li><%= link_to 'Show', product %></li>
                </ul>
              </div>
          </td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if current_user.has_role? :admin %>

<%else%>
  <%= link_to 'Back', root_path %>
<%end%>
<br>


</div>

</div>

app/views/products/new.html.erb
<div class="container">
<h1>New Product</h1>

<%= render 'form', product: @product %>
<br>
<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>


<div class="box-body">
  
<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<p>
  <strong>Prod Name:</strong>
  <%= @product.prod_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
</div>
</div>