config/routes.rb
Rails.application.routes.draw do

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'productdisplays/home'

  get 'admindashboards/show'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'application#hello'
  #devise_for:users
  #devise_for :users, :controllers => { :registrations => "users/registrations",sessions: "users/sessions" }
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "users/registrations",:sessions=>"users/sessions" }
  root 'dashboard#index'

  get 'products99/:id', to: 'dashboard#list_products',as: :list_products

  get 'product_detail/:id' , to:'dashboard#product_detail' , as: :product_detail

  get 'carts/invoicepage'

  #get 'dashboard/list_products/:id'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" ,:registrations => "users/registrations"}

  get 'users/auth/facebook', to: 'sessions#create'
  #get "auth/:provider/callback", to: "sessions#create"
  get 'users/auth/github', to: 'sessions#create'
  # get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  #get '/auth/:provider/callback', to: 'sessions#create'

  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_up', :to => 'devise/registrations#new'
    get 'sign_in', :to => 'devise/sessions#new'
    get 'users/sign_out', :to => 'devise/sessions#destroy'
  end
  #root 'dashboard#index'

  resources :categories
  resources :products
  #resources :carts, only: [:show]
  resources :carts
  resources :order_items, only: [:create, :update, :destroy]

  get "user_mailer/invoicemail"
  get "carts/createinvoice"

  resources :registrations, only: [:new, :create]

  #get "registrations/new"
  #get "registrations/create"
  #get "registrations/:id", to:'registrations/create' , as: :registrations_detail


  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get  '/signup',  to: 'users#new'
  #get '/signup',  to: 'users#edit'

end

app/views/layouts/_adminheader.html.erb
<header class="main-header">
 <!-- Logo -->

   <!-- mini logo for sidebar mini 50x50 pixels -->
   <span class="logo-mini"><b>A</b>LT</span>

 </a>
 <!-- Header Navbar: style can be found in header.less -->
 <nav class="navbar navbar-static-top">
   <!-- Sidebar toggle button-->


   <div class="navbar-custom-menu">
     <ul class="nav navbar-nav">
       <!-- Messages: style can be found in dropdown.less-->
     <!--  <li class="dropdown messages-menu">  -->
       <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> -->
         <!--  <i class="fa fa-envelope-o"></i> -->

         </a>
         <ul class="dropdown-menu">
           <li class="header">You have 4 messages</li>
           <li>
             <!-- inner menu: contains the actual data -->
             <ul class="menu">
               <li><!-- start message -->
                 <a href="#">
                   <div class="pull-left">

                       <%= image_tag('user2-160x160.jpg', :class => "img_circle", alt: "User Image") %>
                   </div>
                   <h4>
                     Support Team
                     <small><i class="fa fa-clock-o"></i> 5 mins</small>
                   </h4>

                 </a>
               </li>
               <!-- end message -->


               <li>
                 <a href="#">
                   <div class="pull-left">

                       <%= image_tag('user3-128x128.jpg', :class => "img_circle", alt: "User Image") %>

                   </div>
                   <h4>
                     Sales Department
                     <small><i class="fa fa-clock-o"></i> Yesterday</small>
                   </h4>
                   <p>Why not buy a new awesome theme?</p>
                 </a>
               </li>
               <li>
                 <a href="#">
                   <div class="pull-left">

                       <%= image_tag('user4-128x128.jpg', :class => "img_circle", alt: "User Image") %>
                   </div>
                   <h4>
                     Reviewers
                     <small><i class="fa fa-clock-o"></i> 2 days</small>
                   </h4>
                   <p>Why not buy a new awesome theme?</p>
                 </a>
               </li>
             </ul>
           </li>
           <li class="footer"><a href="#">See All Messages</a></li>
         </ul>
       </li>


       <!-- User Account: style can be found in dropdown.less -->
       <li class="dropdown user user-menu">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
           <%= image_tag('user2-160x160.jpg', :class => "user-image", alt: "User Image") %>
           <span class="hidden-xs">Rahul Modi</span>
         </a>
         <ul class="dropdown-menu">
           <!-- User image -->
           <li class="user-header">

               <%= image_tag('user2-160x160.jpg', :class => "img_circle", alt: "User Image") %>

             <p>
               Rahul Modi - Web Developer
               <small>Member since Nov. 2012</small>
             </p>
           </li>
           <!-- Menu Body -->

           <!-- Menu Footer-->
           <li class="user-footer">
             <div class="pull-right">
               <%= link_to "Sign out",destroy_user_session_path, method: :delete %>
             </div>
           </li>
         </ul>
       </li>
       <!-- Control Sidebar Toggle Button -->
       <li>
         <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
       </li>
     </ul>
   </div>
 </nav>
</header>

app/views/layouts/_adminsidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>Rahul Modi</p>
        <!-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a> -->
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">

      <li class="header">MAIN NAVIGATION</li>
      <% if current_user.has_role? :admin %>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
      <%end%>
        <li><%= link_to "Products",products_path , :class => 'navbar-link'  %></li>
        <li><%= link_to "Categories",categories_path , :class => 'navbar-link'  %></li>
      <!--  <li><%#= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>-->

    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{current_order.subtotal} )", carts_show_path, class: "btn btn-link" %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Project app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <%= puts current_user%>
        <!--<%# if user_signed_in? %>-->
        <% if current_user %>
          <% if current_user.has_role? :admin %>
            Logged in as <strong><%= current_user.email %></strong>.
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li> |
            <li><%= link_to "Products",products_path , :class => 'navbar-link'  %></li>
            <li><%= link_to "Categories",categories_path , :class => 'navbar-link'  %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
          <% else%>
        <!--<li><%#= link_to "Products",products_path , :class => 'navbar-link'  %></li>
            <li><%#= link_to "Categories",categories_path , :class => 'navbar-link'  %></li>-->
            <% categories.each do |category| %>
                <li><%=link_to category.category_name,list_products_path(category.id)%></li>
            <% end %>
            <!--<li><%#= link_to "My Store", products_path %></li>-->
            <li><h4 class="cart-text"><%= render 'layouts/cart_text'%></h4></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
          <% end %>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li> |
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/adminshow.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Dashboard</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <%=render 'layouts/adminheader'%>

  <%=render 'layouts/adminsidebar'%>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content">
      <%=yield%>
    </section>
  </div>

  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>

  <div class="control-sidebar-bg"></div>
</div>



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%#= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/productshow.html.erb
<% Product.where(category_id: @category.id).each do |product| %>
<li> <%= product.prod_name %> </li>
<% end %>